package frc.robot.commands.teleop.logic;

public enum RobotState {
        DEFAULT,

        COLLECTING, COLLECTING_SLOW,

        POOPING_PREP, POOPING,

        SUBWOOFER_PREP, SUBWOOFER,

        FAST_SUB_PREP, FAST_SUB,

        PODIUM_PREP, PODIUM,

        SHOOTING,

        AMP_PREP, AMP_SCORE, AMP_EXIT,

        CLIMB_INIT, CLIMB_PULLDOWN, CLIMB_LEVEL,

        TRAP_ELEV_MIDWAY, TRAP_WRIST_MIDWAY, TRAP_ELEV_FULL, TRAP_WRIST_FULL, TRAP_SCORE, TRAP_DOTHEJIGGLE,

        PASS,

        RECOVERY_INIT, RECOVERY
}
